colorScheme = "catppuccin"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
replyByEmail = false
disableImageOptimization = false
disableTextInHeader = false
giteaDefaultServer = "https://git.fsfe.org"
forgejoDefaultServer = "https://v8.next.forgejo.org"
defaultBackgroundImage = "MontBlancMassif_1920x1080.jpg"
smartTOC = true
smartTOCHideUnfocusedChildren = ""
highlightCurrentMenuArea = true
mainSections = [ "posts" ]

[header]
layout = "fixed-fill-blur"

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "background"
homepageImage = "MontBlancMassif_1920x1080.jpg"
showRecent = true
showRecentItems = 3
showMoreLink = true
showMoreLinkDest = "/posts/"
cardView = true
cardViewScreenWidth = false
layoutBackgroundBlur = true

[article]
heroStyle = "background"
showDate = true
showViews = true
showLikes = true
showComments = true
showDateOnlyInArticle = false
showDateUpdated = false
showAuthor = false
showHero = true
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = true
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showTaxonomies = true
showAuthorsBadges = false
showWordCount = true
showZenMode = false

[list]
heroStyle = "background"
showHero = true
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = false
showSummary = true
showViews = false
showLikes = false
showTableOfContents = true
showCards = true
orderByWeight = true
groupByYear = false
cardView = true
cardViewScreenWidth = false
constrainItemsWidth = true

[sitemap]
excludedKinds = [ "taxonomy", "term" ]

[taxonomy]
showTermCount = true
showHero = true
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
cardView = false

[term]
showHero = true
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
groupByYear = false
cardView = ""
cardViewScreenWidth = false

[firebase]
apiKey = "AIzaSyAQNvE3yWtMAY2j86hhqqnNpkZU4MUFAkw"
authDomain = "bahmoudd.firebaseapp.com"
projectId = "bahmoudd"
storageBucket = "bahmoudd.firebasestorage.app"
messagingSenderId = "523693964707"
appId = "1:523693964707:web:fed2abc765499dd76dae16"
measurementId = "G-5MQ86THKRR"

[fathomAnalytics]

[umamiAnalytics]

[selineAnalytics]

[buymeacoffee]

[verification]

[rssnext]